version: '3'

services:
  nginx:
    build:
      context: ./srcs/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "80:80"
    networks:
      - my-network
    restart: always

networks:
  my-network:
    driver: bridge