version: "3.9"

services:

  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    image: nginx:1.0
    env_file: .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html/wordpress
    restart: always

  wordpress:
    container_name: wordpress
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:1.0
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html/wordpress
    restart: always

  mariadb:
    container_name: mariadb
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:1.0
    env_file: .env
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: always

volumes:
  wordpress:
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jrossett/data/wordpress'
  mariadb:
    driver_opts: 
      type: 'none'
      o: 'bind'
      device: '/home/jrossett/data/mariadb'

networks:
  inception:
    driver: bridge